name: Test Moon Generator

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run test
        run: python generate.py

      - name: Upload Moon calendar
        uses: actions/upload-artifact@v4
        with:
          name: Moon-calendar
          path: Moon.ics
